# Site settings
title: CMD+U Conference
email: hello@cmduconf.com
description: CMD+U Conference is the first conference for iOS / OSX and Swift Developers entirely focused on testing (from unit tests to end-to-end tests). Held in Barcelona on the 8th of July!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cmduconf.com" # the base hostname & protocol for your site
twitter_username: cmduconf
github_username: cmduconf

# Build settings
markdown: kramdown
permalink: none
highlighter: rouge
timezone: Europe/Madrid
encoding: utf-8
paginate_path: "blog/page:num"

#external urls
lyst_web: http://lyst.com
